name: Angular CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Npm install Angular with all dependencies
      run: |
        npm install -g @angular/cli
        npm install -g @angular-devkit/build-angular
        npm install -g @angular/compiler-cli
        npm install -g typescript
        npm install -g @angular/compiler
    - name: Link and build project
      run: |
        rm -rf ./dist
        npm link
        ng build --prod
    - name: Verify installation
      working-directory: ${{ github.workspace }}
      run: ls -la ./dist
