name: Angular CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Npm install Angular with all dependencies
      run: |
        npm install -g @angular/cli
        npm install -g @angular-devkit/build-angular
        npm install -g @angular/compiler-cli
        npm install -g typescript
        npm install -g @angular/compiler
    - name: Link and build project
      run: |
        rm -rf ./dist
        npm link
        ng build --prod
    - name: Verify installation
      working-directory: ${{ github.workspace }}
      run: ls -la ./dist
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: ftp
        PORT: 21
        LOCAL_DIR: ./dist 
        REMOTE_DIR: /qa.workzy.eu 
        ARGS: --verbose --dry-run	
