name: Angular CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: npm install and npm run build
      run: |
        rm -rf ./dist
        ng build --prod
