name: Angular CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Npm install Angular with all dependencies
      run: |
        npm install -g @angular/cli
        npm install -g @angular-devkit/build-angular
        npm install -g @angular/compiler-cli
        npm install -g typescript
        npm install -g @angular/compiler
    - name: Link and build project
      run: |
        rm -rf ./dist
        npm link
        ng build --prod
    - name: Verify installation
      working-directory: ${{ github.workspace }}
      run: ls -la ./dist
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        ftp_server: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        method: ftp
        port: 21
        local_dir: ./dist 
        remote_dir: /qa.workzy.eu 
        ARGS: --verbose --dry-run	
